steps:
- name: 'gcr.io/cloud-builders/java/mvn'
  args: ['clean', 'install']
  id: 'maven-build'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/manager:$BRANCH_NAME-$REVISION_ID', '.']
  id: 'docker-build'
  waitFor: ['maven-build']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/manager:$BRANCH_NAME-$REVISION_ID"]
  id: 'docker-push'
  waitFor: ['docker-build']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - beta
  - container
  - clusters
  - get-credentials
  - standard-cluster-1	
  - --zone=$_ZONE
  - --project=$PROJECT_ID
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '--filename=deployment.yaml'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '--filename=service.yaml'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials standard-cluster-1 --zone $_ZONE -a
    kubectl set image deployment/manager manager=gcr.io/$PROJECT_ID/manager:$BRANCH_NAME-$REVISION_ID
