apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: manager
spec:
  replicas: 2
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        imagePullPolicy: Always
        image: gcr.io/aws-asha/manager:latest
        resources:
          limits:
            memory: 2048Mi
          requests:
            memory: 512Mi
        ports:
        - containerPort: 8080