kind: Service
apiVersion: v1
metadata:
  name: manager-service
spec:
  selector:
    app: manager
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
    name: gui-service
  type: LoadBalancer
